# Generated by Django 3.0.6 on 2020-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_date', models.DateTimeField(auto_now=True)),
                ('blog_text', models.TextField(max_length=10000)),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
